# Generated by Django 5.0.4 on 2024-05-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='serie',
        ),
        migrations.CreateModel(
            name='EpisodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoflixApp.episode')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoflixApp.serie')),
            ],
        ),
        migrations.AddField(
            model_name='serie',
            name='episodeList',
            field=models.ManyToManyField(through='videoflixApp.EpisodeList', to='videoflixApp.episode'),
        ),
    ]
