# Generated by Django 5.0.4 on 2024-04-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixApp', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short',
        ),
    ]
