# Generated by Django 5.0.4 on 2024-04-26 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixApp', '0003_remove_user_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('genre', models.CharField(default=' ', max_length=100)),
                ('type', models.CharField(default=' ', max_length=100)),
                ('fsk', models.CharField(default=' ', max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
    ]
