# Generated by Django 5.0.4 on 2024-05-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixApp', '0005_myliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='inList',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='inList',
            field=models.BooleanField(default=False),
        ),
    ]
