# Generated by Django 5.0.4 on 2024-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflixApp', '0006_serie_inlist_video_inlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
